Repository FACG6/leannky-Anty, pull requests merged in 2019-03, with the labels that each got.

#47 backend signup validation
  src/controller/home.js
  src/controller/index.js
  src/controller/middleware/validation.js
  src/views/home.hbs
Labels: waiting review

#61 Login back end
  public/js/domUser.js
  public/js/domUserQ.js
  public/js/home.js
  src/controller/home.js
  src/controller/index.js
  src/controller/middleware/getToken.js
  src/controller/middleware/isfound.js
  src/controller/middleware/validation.js
  src/controller/user/userProfile.js
  src/controller/user/userQ.js
  src/database/queries/addPost.js
  src/views/consProfile.hbs
  src/views/home.hbs
  src/views/layouts/cons.hbs
  src/views/layouts/user.hbs
  src/views/partials/userHeader.hbs
  src/views/userProfile.hbs
  src/views/userQ.hbs
Labels: routes

#74 Consultant profile page front end and back-end
  public/css/cons.css
  public/js/domCons.js
  src/controller/consultant/addAns.js
  src/controller/consultant/consAns.js
  src/controller/consultant/consGetNotAns.js
  src/controller/consultant/consProfile.js
  src/controller/index.js
  src/controller/middleware/renderForCons.js
  src/controller/user/userPrevQ.js
  src/database/build.sql
  src/database/connection.js
  src/database/queries/addAns.js
  src/database/queries/getConsAns.js
  src/database/queries/getMyAns.js
  src/database/queries/getNotAns.js
  src/views/consAns.hbs
  src/views/consProfile.hbs
  src/views/layouts/cons.hbs
  src/views/partials/consHeader.hbs
  src/views/partials/userHeader.hbs
Labels: completed

#83 Routing, adding, updating tests
  package-lock.json
  package.json
  public/js/domCons.js
  public/js/domUserQ.js
  src/app.js
  src/controller/consultant/addAns.js
  src/controller/middleware/authentication.js
  src/controller/middleware/getToken.js
  src/controller/middleware/isfound.js
  src/controller/middleware/renderMyPosts.js
  src/controller/middleware/validation.js
  src/controller/user/userQ.js
  src/database/build.js
  src/database/build.sql
  src/database/connection.js
  src/database/queries/addPost.js
  test/test.js
Labels: completed

#85 Cons style
  public/css/cons.css
  public/js/domCons.js
  src/views/consAns.hbs
Labels: in progress
